name: "Build Extension .zip" # i cate hrx

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: # is ts the formatting?
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip extension # dont zip .github because .github no cool
        run: zip -r spicetown-use-this.zip . -x "spicetown-use-this.zip" "*.git*" "*.github*"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: spicetown-unzip
          path: spicetown-use-this.zip
          retention-days: 5